micronaut:
  application:
    name: desafioPix

datasources:
  default:
    url: jdbc:mariadb://127.0.0.1:3306/pix
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: ""


#datasources:
#  default:
#    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password: ""
#    driverClassName: org.h2.Driver

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
